# Metadata Filtering
- 벡터 유사도 계산 전에(또는 함께) 문서의 메타데이터 조건으로 검색 대상을 제한하는 기법

In [2]:
%pip install lark

Collecting lark
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Downloading lark-1.3.1-py3-none-any.whl (113 kB)
Installing collected packages: lark
Successfully installed lark-1.3.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
from dotenv import load_dotenv
import os

load_dotenv()
os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
os.environ['PINECONE_API_KEY'] = os.getenv('PINECONE_API_KEY')
os.environ['COHERE_API_KEY'] = os.getenv('COHERE_API_KEY')

os.environ['LANGSMITH_TRACING'] = 'true'
os.environ['LANGSMITH_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGSMITH_PROJECT'] = 'skn34-langchain'
os.environ['LANGSMITH_API_KEY'] = os.getenv('LANGSMITH_API_KEY')

In [2]:
import pandas as pd

document_df = pd.read_csv('documents_meta.csv')
document_df

,doc_id,title,content,author,category
0,D1,제주도 여행 가이드,"제주도는 대한민국의 대표 관광지로서, 한라산 등반, 성산 일출봉 관광, 해변 활동(...",김민수,여행
1,D2,전주 비빔밥과 진주 비빔밥 차이점,"비빔밥은 조선 시대부터 전해 내려온 대표적 한국 음식으로, 밥 위에 고명(채소·고기...",이영희,음식
2,D3,걸스데이 히트곡 분석,"걸스데이는 2010년 데뷔한 대한민국의 4인조 걸그룹으로, 대표곡으로는 “Somet...",박지훈,문화;음악
3,D4,세종대왕과 훈민정음,세종대왕(1397~1450)은 훈민정음을 창제하여 한글을 보급한 조선의 4대 임금입...,최수정,역사;교육
4,D5,이순신 장군의 명량 해전,이순신 장군(1545~1598)은 임진왜란 당시 명량 해전에서 13척의 배로 133...,정우성,역사;군사
5,D6,2024년 기후 변화 종합 보고서,"2024년 전 지구 평균 기온은 산업화 이전 대비 약 1.2℃ 상승했으며, 해수면 ...",한예슬,환경;과학;보고서
6,D7,AI 기술 동향 및 윤리,"최근 인공지능 분야에서는 생성형 AI, 멀티모달 모델, 강화학습 기반 에이전트 개발...",강다니엘,기술;윤리;AI
7,D8,서울 지하철 이용 가이드,"서울 지하철은 1호선부터 9호선까지 운행되며, 주요 환승역으로는 서울역·강남역·종로...",오정연,교통;여행
8,D9,판소리 “춘향가” 서사 구조,"판소리는 소리꾼과 고수가 함께 공연하는 한국 전통 음악으로, 대표 작품에는 “춘향가...",신동엽,문화;음악;역사
9,D10,한국 축구 대표팀 주요 기록,"한국 축구 대표팀은 2002 한일 월드컵 4강 진출, 2012 런던 올림픽 동메달 ...",윤아름,스포츠;역사
10,D11,건강한 생활습관 가이드,"건강을 위해서는 규칙적 식습관, 적절한 운동(주 3회 이상, 유산소+근력), 충분한...",김민수,건강;생활
11,D12,서울 근교 당일치기 여행지,"서울 근교에서 당일치기로 다녀올 만한 여행지로는 가평 쁘띠프랑스, 남양주 수종사, ...",이영희,여행;레저
12,D13,전국 비빔밥 영양 성분 분석,"비빔밥은 지역별로 칼로리, 탄수화물, 단백질, 지방 함량이 차이를 보입니다. 전주 ...",박지훈,음식;영양;건강
13,D14,AI 기반 기후 예측 연구 사례,AI를 활용한 기후 예측 연구는 기계학습 모델을 통해 대규모 기상 데이터를 분석해 ...,최수정,기술;환경;과학
14,D15,한국 전통 음악 “가야금”,"가야금은 한국 전통 현악기로, 12개의 줄을 가진 칠현금(七絃琴) 계열 악기입니다....",정우성,문화;음악;역사
15,D16,한국 전통 혼례 풍습,"전통 혼례는 예식 절차가 복잡하며, 폐백, 예단, 함, 폐백음식 등 여러 의례가 포...",한예슬,문화;역사;의식
16,D17,2023년 한국 영화 흥행 Top10,"2023년 한국 영화 흥행 순위 Top10에는 “헌트”, “비상선언”, “범죄도시3...",강다니엘,문화;영화;엔터테인먼트
17,D18,윈도우즈에서 한글 시각화 설정 방법,"윈도우즈 환경에서 한글이 깨지지 않고 시각화(그래프·차트)할 때는, 한글 폰트를 시...",오정연,기술;소프트웨어;설치
18,D19,코드 악취와 리팩토링 개요,코드 악취(Bad Smell)는 설계·구현 단계에서 코드 구조가 비효율적이거나 유지...,신동엽,기술;프로그래밍;소프트웨어 개발
19,D20,JUnit5와 JUnit4 차이점,JUnit5는 모듈화된 구조(Java Platform Module System 지원...,윤아름,기술;프로그래밍;테스팅
20,D21,Wheel of Fortune 게임 구조,Wheel of Fortune은 랜덤으로 숫자·문자가 배치된 원판을 돌려 맞춰진 알...,김민수,게임;엔터테인먼트;기술
21,D22,싱글톤 디자인 패턴 예제,"싱글톤(Singleton) 패턴은 클래스의 인스턴스를 한 개만 생성하도록 보장하며,...",이영희,기술;프로그래밍;소프트웨어 개발
22,D23,Strategy 패턴 설명,Strategy 패턴은 알고리즘 군을 캡슐화하여 상호 교환 가능하도록 만드는 패턴입...,박지훈,기술;프로그래밍;소프트웨어 개발
23,D24,Command 패턴 적용 사례,"Command 패턴은 요청을 객체로 캡슐화하여 요청을 매개변수화하고, 호출자(inv...",최수정,기술;프로그래밍;소프트웨어 개발
24,D25,2025년 한국 AI 정책 보고서,"2025년 한국 정부는 “AI 국가전략 2.0”을 발표하며, 인공지능 기술 연구·개...",정우성,정책;기술;보고서
25,D26,딥러닝 기반 기상 예측 모델,"딥러닝 모델(예: LSTM, Transformer 기반 시계열 모델)을 활용한 기상...",한예슬,기술;과학;환경
26,D27,ChromaDB vs Qdrant 비교,"ChromaDB와 Qdrant는 벡터 검색 라이브러리로, ChromaDB는 오픈소스...",강다니엘,기술;데이터베이스;비교
27,D28,Contextual Compression 개념,Contextual Compression은 긴 텍스트에서 핵심 정보만 추출해 압축(...,오정연,기술;AI;검색
28,D29,Self-Query Retriever 원리,Self-Query Retriever는 문서 메타데이터(제목·요약·키워드)를 분석해...,신동엽,기술;AI;검색
29,D30,Multi-Hop Retrieval 예시,Multi-Hop Retrieval은 한 단계의 검색으로 해결되지 않는 복합 질문에...,윤아름,기술;AI;검색

In [3]:
queries_df = pd.read_csv('queries_meta_v2.csv')
queries_df

,query_id,query_text,relevant_doc_ids
0,Q01,저자 김민수의 문서를 모두 보여줘,D1=1;D11=1;D21=1
1,Q02,저자 이영희의 문서를 모두 보여줘,D2=1;D12=1;D22=1
2,Q03,저자 박지훈의 문서를 모두 보여줘,D3=1;D13=1;D23=1
3,Q04,저자 최수정의 문서를 모두 보여줘,D4=1;D14=1;D24=1
4,Q05,저자 정우성의 문서를 모두 보여줘,D5=1;D15=1;D25=1
5,Q06,저자 한예슬의 문서를 모두 보여줘,D6=1;D16=1;D26=1
6,Q07,저자 강다니엘의 문서를 모두 보여줘,D7=1;D17=1;D27=1
7,Q08,저자 오정연의 문서를 모두 보여줘,D8=1;D18=1;D28=1
8,Q09,저자 신동엽의 문서를 모두 보여줘,D9=1;D19=1;D29=1
9,Q10,저자 윤아름의 문서를 모두 보여줘,D10=1;D20=1;D30=1
10,Q11,카테고리 AI에 해당하는 문서를 찾아줘,D7=1;D28=1;D29=1;D30=1
11,Q12,카테고리 건강에 해당하는 문서를 찾아줘,D11=1;D13=1
12,Q13,카테고리 검색에 해당하는 문서를 찾아줘,D28=1;D29=1;D30=1
13,Q14,카테고리 게임에 해당하는 문서를 찾아줘,D21=1
14,Q15,카테고리 과학에 해당하는 문서를 찾아줘,D6=1;D14=1;D26=1
15,Q16,카테고리 교육에 해당하는 문서를 찾아줘,D4=1
16,Q17,카테고리 교통에 해당하는 문서를 찾아줘,D8=1
17,Q18,카테고리 군사에 해당하는 문서를 찾아줘,D5=1
18,Q19,카테고리 기술에 해당하는 문서를 찾아줘,D7=1;D14=1;D18=1;D19=1;D20=1;D21=1;D22=1;D23=1
19,Q20,카테고리 데이터베이스에 해당하는 문서를 찾아줘,D27=1
20,Q21,저자 김민수이(가) 쓴 게임 카테고리 문서를 보여줘,D21=1
21,Q22,저자 이영희이(가) 쓴 프로그래밍 카테고리 문서를 보여줘,D22=1
22,Q23,저자 박지훈이(가) 쓴 음식 카테고리 문서를 보여줘,D13=1
23,Q24,저자 최수정이(가) 쓴 환경 카테고리 문서를 보여줘,D14=1
24,Q25,저자 정우성이(가) 쓴 음악 카테고리 문서를 보여줘,D15=1
25,Q26,카테고리가 AI이거나 건강인 문서를 보여줘,D7=1;D11=1;D13=1;D28=1;D29=1;D30=1
26,Q27,카테고리가 건강이거나 검색인 문서를 보여줘,D11=1;D13=1;D28=1;D29=1;D30=1
27,Q28,카테고리가 검색이거나 게임인 문서를 보여줘,D21=1;D28=1;D29=1;D30=1
28,Q29,카테고리가 게임이거나 과학인 문서를 보여줘,D6=1;D14=1;D21=1;D26=1
29,Q30,카테고리가 과학이거나 교육인 문서를 보여줘,D4=1;D6=1;D14=1;D26=1